// <auto-generated />
using System;
using DAO_ReputationService.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAO_ReputationService.Migrations
{
    [DbContext(typeof(dao_reputationserv_context))]
    [Migration("20211113105754_db_init")]
    partial class db_init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("DAO_ReputationService.Models.UserReputationHistory", b =>
                {
                    b.Property<int>("UserReputationHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<double>("EarnedAmount")
                        .HasColumnType("double");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<double>("LastStakedTotal")
                        .HasColumnType("double");

                    b.Property<double>("LastTotal")
                        .HasColumnType("double");

                    b.Property<double>("LastUsableTotal")
                        .HasColumnType("double");

                    b.Property<double>("LostAmount")
                        .HasColumnType("double");

                    b.Property<double>("StakeReleasedAmount")
                        .HasColumnType("double");

                    b.Property<double>("StakedAmount")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserReputationHistoryID");

                    b.ToTable("UserReputationHistories");
                });

            modelBuilder.Entity("DAO_ReputationService.Models.UserReputationStake", b =>
                {
                    b.Property<int>("UserReputationStakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ReferenceID")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceProcessID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserReputationStakeID");

                    b.ToTable("UserReputationStakes");
                });
#pragma warning restore 612, 618
        }
    }
}
